name: LocalStack Demo
# run-name: ${{ github.actor }} is testing out local stack with GitHub Actions 🚀

on: 
  push:
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  Check-arch:
    runs-on: ubuntu-latest
    steps:
      - run: uname -m
      - run: docker version
  Setup-LocalStack-and-TF:
    runs-on: ubuntu-latest
    steps:
      # - name: Install
      #   run:
      #     | 
      #       curl --output localstack-cli-4.9.1-linux-amd64-onefile.tar.gz --location https://github.com/localstack/localstack-cli/releases/download/v4.9.1/localstack-cli-4.9.1-linux-amd64-onefile.tar.gz
      #       sudo tar xvzf localstack-cli-4.9.1-linux-*-onefile.tar.gz -C /usr/local/bin
      - name: Setup LocalStack
        uses: localstack/setup-localstack@v0.2.4
      - run: localstack --version
      # - name: Start LocalStack
      #   run:
      #     |
      #       localstack auth set-token ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
      #       localstack start -d
      - name: Troubleshooting LocalStack
        run:
          | 
            localstack logs
            curl -s localhost:4566/_localstack/diagnose
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - run: terraform version
      - name: Create heredoc .TF file
        run:
          |
            cat << EOF > main.tf
            provider "aws" {
            
              access_key                  = "mock_access_key"
              secret_key                  = "mock_secret_key"
              region                      = "us-east-1"
            
              s3_use_path_style           = true
              skip_credentials_validation = true
              skip_metadata_api_check     = true
              skip_requesting_account_id  = true
            
              endpoints {
                s3             = "http://s3.localhost.localstack.cloud:4566"
              }
            }
            resource "aws_s3_bucket" "test-bucket" {
              bucket = "my-bucket"
            }
            EOF
      - name: Plan and Apply
        run: 
          | 
            terraform init
            terraform fmt
            terraform validate
            terraform plan -out planbucket
            terraform apply -auto-approve planbucket
      - name: List resource
        run: 
          |
            awslocal s3 ls
            
