name: LocalStack Demo
# run-name: ${{ github.actor }} is testing out local stack with GitHub Actions 🚀

on: 
  # push:
  #   paths-ignore:
  #     - '*.md'
  workflow_dispatch:

jobs:
  Check-arch:
    runs-on: ubuntu-latest
    steps:
      - run: uname -m
      - run: docker info
  Setup-LocalStack-and-TF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install LocalStack
        run:
          | 
            curl --output localstack-cli-4.9.1-linux-amd64-onefile.tar.gz --location https://github.com/localstack/localstack-cli/releases/download/v4.9.1/localstack-cli-4.9.1-linux-amd64-onefile.tar.gz
            sudo tar xvzf localstack-cli-4.9.1-linux-*-onefile.tar.gz -C /usr/local/bin
      # - name: Setup LocalStack
      #   uses: localstack/setup-localstack@v0.2.4
      - run: localstack --version
      - name: Start LocalStack and set auth token
        run:
          |
            localstack auth set-token ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
            localstack start -d
      - name: Install awslocal cli
        run:
          |
            pip install awscli-local
      - name: List resource
        run: 
          |
            awslocal s3 ls
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - run: terraform version
      - name: Troubleshooting LocalStack
        run:
          | 
            localstack logs
            # curl -s localhost:4566/_localstack/diagnose
      - name: Plan and Apply
        run: 
          | 
            cd terraform
            terraform init
            terraform fmt
            terraform validate
            terraform plan -out planeks
            terraform apply -auto-approve planeks
      - name: List resource
        run: 
          |
            awslocal eks list-clusters
      - name: Configure kubectl
        run:
          |
            aws configure set aws_access_key_id mock_access_key
            aws configure set aws_secret_access_key mock_secret_key
            aws configure set default.region us-east-1
            awslocal eks update-kubeconfig --name php-cluster 
            kubectl config use-context arn:aws:eks:us-east-1:000000000000:cluster/php-cluster
            kubectl get nodes -o wide
            
