name: LocalStack Demo
run-name: ${{ github.actor }} is testing out local stack with GitHub Actions 🚀

on: 
  push:
  workflow_dispatch:

jobs:
  Check-arch:
    runs-on: ubuntu-latest
    steps:
      - run: uname -m
      - run: docker version
  Setup-local-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run:
          | 
            curl --output localstack-cli-4.9.1-linux-amd64-onefile.tar.gz --location https://github.com/localstack/localstack-cli/releases/download/v4.9.1/localstack-cli-4.9.1-linux-amd64-onefile.tar.gz
            sudo tar xvzf localstack-cli-4.9.1-linux-*-onefile.tar.gz -C /usr/local/bin
      - run: localstack --version
            
