name: ci

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: ./Basic-PHP-RESTful-API
          load: true
          tags: "teste"

      - name: Scan Image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "teste"
          fail-build: true
          output-format: sarif

      - name: Upload Anchore Scan SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      

  build:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - run: whoami
      - run: sudo -s

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          context: ./Basic-PHP-RESTful-API
          call: check

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: ./Basic-PHP-RESTful-API
          load: true
          tags: "teste"

      - name: Test
        run: |
          docker run -dp 8000:8000 --name teste teste
          docker ps
          curl -X POST http://0.0.0.0:8000/api/users -d "name=John Doe&age=30&job=Developer"
          docker rm -f teste

  push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./Basic-PHP-RESTful-API
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
