name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - run: 
          |
            cd Basic-PHP-RESTful-API
            pwd
            ls

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          context: ./Basic-PHP-RESTful-API
          call: check

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: ./Basic-PHP-RESTful-API
          load: true
          tags: "teste"

      - name: Test
        run: |
          docker run --rm teste

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./Basic-PHP-RESTful-API
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
